# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'player.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setStyleSheet("background-color: rgb(51, 51, 51);")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(40, 60, -1, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setMinimumSize(QtCore.QSize(220, 60))
        self.widget.setMaximumSize(QtCore.QSize(220, 60))
        self.widget.setStyleSheet("border:2px solid;\n"
"border-radius:20%;\n"
"border-color:#4f4f4f")
        self.widget.setObjectName("widget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_11.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(15)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.tech_icon = QtWidgets.QLabel(self.widget)
        self.tech_icon.setMinimumSize(QtCore.QSize(50, 50))
        self.tech_icon.setMaximumSize(QtCore.QSize(50, 50))
        self.tech_icon.setBaseSize(QtCore.QSize(60, 60))
        self.tech_icon.setStyleSheet("border-image: url(:/img/AR教学视频v1.0/assets/finish_icon_score.png.png);\n"
"border:NONE\n"
"")
        self.tech_icon.setText("")
        self.tech_icon.setObjectName("tech_icon")
        self.horizontalLayout_11.addWidget(self.tech_icon)
        self.tech_name = QtWidgets.QLabel(self.widget)
        self.tech_name.setMinimumSize(QtCore.QSize(120, 55))
        self.tech_name.setMaximumSize(QtCore.QSize(120, 55))
        self.tech_name.setStyleSheet("border:NONE\n"
"")
        self.tech_name.setTextFormat(QtCore.Qt.RichText)
        self.tech_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tech_name.setObjectName("tech_name")
        self.horizontalLayout_11.addWidget(self.tech_name, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_3.addWidget(self.widget)
        spacerItem = QtWidgets.QSpacerItem(5, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(40, 0, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setMinimumSize(QtCore.QSize(182, 40))
        self.widget_2.setMaximumSize(QtCore.QSize(182, 40))
        self.widget_2.setStyleSheet("border:2px solid;\n"
"border-radius:15px;\n"
"border-color:#4f4f4f;")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_12.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(15)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.course_icon = QtWidgets.QLabel(self.widget_2)
        self.course_icon.setMinimumSize(QtCore.QSize(30, 30))
        self.course_icon.setMaximumSize(QtCore.QSize(30, 30))
        self.course_icon.setStyleSheet("image: url(:/img/AR教学视频v1.0/assets/play page_Yoga.png.png);\n"
"border:NONE;\n"
"")
        self.course_icon.setText("")
        self.course_icon.setObjectName("course_icon")
        self.horizontalLayout_12.addWidget(self.course_icon)
        self.course_name = QtWidgets.QLabel(self.widget_2)
        self.course_name.setMinimumSize(QtCore.QSize(100, 30))
        self.course_name.setMaximumSize(QtCore.QSize(100, 30))
        self.course_name.setStyleSheet("border:NONE;")
        self.course_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.course_name.setObjectName("course_name")
        self.horizontalLayout_12.addWidget(self.course_name)
        self.horizontalLayout_4.addWidget(self.widget_2)
        spacerItem1 = QtWidgets.QSpacerItem(0, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 60, 40, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.time = QtWidgets.QLabel(Dialog)
        self.time.setObjectName("time")
        self.horizontalLayout_10.addWidget(self.time, 0, QtCore.Qt.AlignRight)
        self.gridLayout.addLayout(self.horizontalLayout_10, 0, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(5, -1, -1, 0)
        self.horizontalLayout_7.setSpacing(30)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_4 = QtWidgets.QWidget(Dialog)
        self.widget_4.setMinimumSize(QtCore.QSize(240, 40))
        self.widget_4.setMaximumSize(QtCore.QSize(240, 40))
        self.widget_4.setStyleSheet("border:2px solid;\n"
"border-radius:15px;\n"
"border-color:#4f4f4f;")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_14.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_14.setContentsMargins(9, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(10)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.cal_icon = QtWidgets.QLabel(self.widget_4)
        self.cal_icon.setMinimumSize(QtCore.QSize(30, 30))
        self.cal_icon.setMaximumSize(QtCore.QSize(30, 30))
        self.cal_icon.setStatusTip("")
        self.cal_icon.setStyleSheet("image: url(:/img/AR教学视频v1.0/assets/finish_icon_calories.png.png);\n"
"border:NONE;\n"
"")
        self.cal_icon.setLineWidth(0)
        self.cal_icon.setMidLineWidth(0)
        self.cal_icon.setText("")
        self.cal_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.cal_icon.setWordWrap(False)
        self.cal_icon.setObjectName("cal_icon")
        self.horizontalLayout_14.addWidget(self.cal_icon)
        self.label_11 = QtWidgets.QLabel(self.widget_4)
        self.label_11.setMinimumSize(QtCore.QSize(150, 30))
        self.label_11.setMaximumSize(QtCore.QSize(150, 30))
        self.label_11.setStyleSheet("border:NONE;")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_14.addWidget(self.label_11, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_7.addWidget(self.widget_4)
        self.cal_num = QtWidgets.QLabel(Dialog)
        self.cal_num.setObjectName("cal_num")
        self.horizontalLayout_7.addWidget(self.cal_num)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(0, 60, -1, -1)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_3 = QtWidgets.QWidget(Dialog)
        self.widget_3.setMinimumSize(QtCore.QSize(220, 60))
        self.widget_3.setMaximumSize(QtCore.QSize(220, 60))
        self.widget_3.setStyleSheet("border:2px solid;\n"
"border-radius:20%;\n"
"border-color:#4f4f4f")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_13.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(15)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.user_icon = QtWidgets.QLabel(self.widget_3)
        self.user_icon.setMinimumSize(QtCore.QSize(50, 50))
        self.user_icon.setMaximumSize(QtCore.QSize(50, 50))
        self.user_icon.setBaseSize(QtCore.QSize(60, 60))
        self.user_icon.setStyleSheet("border-image: url(:/img/AR教学视频v1.0/res/user_icon.jpg);\n"
"border:NONE;")
        self.user_icon.setText("")
        self.user_icon.setObjectName("user_icon")
        self.horizontalLayout_13.addWidget(self.user_icon)
        self.user_name = QtWidgets.QLabel(self.widget_3)
        self.user_name.setMinimumSize(QtCore.QSize(120, 55))
        self.user_name.setMaximumSize(QtCore.QSize(145, 55))
        self.user_name.setStyleSheet("border:NONE\n"
"")
        self.user_name.setTextFormat(QtCore.Qt.RichText)
        self.user_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.user_name.setObjectName("user_name")
        self.horizontalLayout_13.addWidget(self.user_name, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_5.addWidget(self.widget_3)
        spacerItem2 = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(5, -1, 40, 0)
        self.horizontalLayout_8.setSpacing(30)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_5 = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setMinimumSize(QtCore.QSize(225, 40))
        self.widget_5.setMaximumSize(QtCore.QSize(225, 40))
        self.widget_5.setStyleSheet("border:2px solid;\n"
"border-radius:15px;\n"
"border-color:#4f4f4f;")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_15.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_15.setContentsMargins(9, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(10)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_16 = QtWidgets.QLabel(self.widget_5)
        self.label_16.setMinimumSize(QtCore.QSize(30, 30))
        self.label_16.setMaximumSize(QtCore.QSize(30, 30))
        self.label_16.setStyleSheet("image: url(:/img/AR教学视频v1.0/assets/finish_icon_score.png.png);\n"
"border:NONE;\n"
"")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_15.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.widget_5)
        self.label_17.setMinimumSize(QtCore.QSize(150, 30))
        self.label_17.setMaximumSize(QtCore.QSize(150, 30))
        self.label_17.setStyleSheet("border:NONE;")
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_15.addWidget(self.label_17, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_8.addWidget(self.widget_5, 0, QtCore.Qt.AlignLeft)
        self.goal_num = QtWidgets.QLabel(Dialog)
        self.goal_num.setObjectName("goal_num")
        self.horizontalLayout_8.addWidget(self.goal_num)
        self.gridLayout.addLayout(self.horizontalLayout_8, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.gridLayout_2.setRowStretch(0, 1)
        self.gridLayout_2.setRowStretch(1, 6)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.tech_name.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:26pt; color:#ffffff;\">陈老师</span></p></body></html>"))
        self.course_name.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; color:#fff;\">瑜伽一段</span></p></body></html>"))
        self.time.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:24pt; color:#ffffff;\">08:56:03</span></p></body></html>"))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">消耗卡路里</span></p></body></html>"))
        self.cal_num.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:42pt; color:#fff;\">320</span><span style=\" font-size:22pt; color:#939a99;\">千卡</span></p></body></html>"))
        self.user_name.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-family:\'PingFang SC\'; font-size:26pt; color:#ffffff;\">测试用户</span></p></body></html>"))
        self.label_17.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">得分</span></p></body></html>"))
        self.goal_num.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:42pt; color:#fff;\">89</span><span style=\" font-size:22pt; color:#939a99;\">/100分</span></p></body></html>"))

import res_rc
